// GENERATED by board-ab setup from git tag v1-baseline-2026-09-28 src/App.tsx (useMemo unwrapped) — the v1 reference.
// Do not edit by hand: it is the "before" side of the A/B.
import type { Token } from '../../src/lib/rules.ts';
const byLiq = (a: Token, b: Token) => (b.liq ?? -1) - (a.liq ?? -1);
const LP_DESC: Record<string, string> = {
  'Argus pad': 'Minted by the Argus launchpad contracts (the ARGUS team) — GLITCH and most Arc meme launches.',
  'faze.fun': 'Minted by the faze.fun launchpad.',
  'Warp': 'Launched on Warp and still on its bonding curve.',
  'Launchpad': 'Minted by a token-factory contract that has launched several Arc tokens.',
};
export function v1Board(tokens: Token[], PINNED: Set<string>, st: any) {
  const { filter, q, sort, dir, hideDupes, showInactive, heroQ } = st;
  const MIN_HOLDERS = 50; const MIN_VOL_24H = 50;
  const active = (t: Token) => t.isEcosystem || PINNED.has(t.address.toLowerCase()) || (t.volume24h ?? 0) >= MIN_VOL_24H;
  const { canonical, tickerCount } = (() => {
    const best = new Map<string, { addr: string; score: number }>();
    const count = new Map<string, number>();
    for (const t of tokens) {
      const s = (t.symbol || '').toUpperCase(); if (!s) continue;
      count.set(s, (count.get(s) || 0) + 1);
      // Ecosystem/core tokens (native USDC, Animus…) are always the real one for their ticker. Otherwise
      // HOLDERS decide (an impersonator has ~0 holders; the real token has thousands) — ranking by liquidity
      // let a fake with a wash-traded pool win. Liquidity is only the tiebreak when holders are equal/unknown.
      // Pinned real tokens (by ADDRESS) always own their ticker — a fake "CRCL" airdropped to 25,745 wallets outranked the real one.
      const score = (t.isEcosystem || PINNED.has(t.address.toLowerCase()) ? 1e18 : 0) + (t.holders ?? 0) * 1e9 + (t.liq ?? 0);
      const cur = best.get(s);
      if (!cur || score > cur.score) best.set(s, { addr: t.address.toLowerCase(), score });
    }
    return { canonical: new Set([...best.values()].map((v) => v.addr)), tickerCount: count };
  })();
  // A duplicate ticker OR a row that failed the hard rules (sanitizeToken: impossible numbers, Circle impersonator) is hidden
  // from the default screener, the dashboard and every total. Search still finds it, with the bad numbers blanked.
  const isDup = (t: Token) => !!(t as any).bad || ((tickerCount.get((t.symbol || '').toUpperCase()) ?? 0) > 1 && !canonical.has(t.address.toLowerCase()));
  const dupCount = (() => tokens.filter(isDup).length)(); // eslint-disable-line

  const rows = (() => {
    let r = tokens;
    if (filter === 'new') r = r.filter((t) => t.launchpad);
    else if (filter === 'eco') r = r.filter((t) => t.isEcosystem);
    const s = q.trim().toLowerCase();
    if (s) {
      // While searching, show EVERY match (incl. duplicates) so a specific token is findable.
      r = r.filter((t) => t.name.toLowerCase().includes(s) || t.symbol.toLowerCase().includes(s) || t.address.toLowerCase().includes(s));
      const rank = (t: Token) => {
        const sym = t.symbol.toLowerCase(), nm = t.name.toLowerCase();
        if (sym === s || t.address.toLowerCase() === s) return 0;
        if (sym.startsWith(s)) return 1;
        if (nm.startsWith(s)) return 2;
        return 3;
      };
      // Exact/prefix matches first, then by liquidity — real USDC beats 11 lookalikes.
      return [...r].sort((a, b) => (rank(a) - rank(b)) || ((b.liq ?? -1) - (a.liq ?? -1)));
    }
    // Default view: drop fully-dead tokens (no price/liq/holders/volume) and, unless toggled, impersonators.
    r = r.filter((t) => t.price != null || t.liq != null || (t.holders ?? 0) > 0 || t.volume24h != null);
    if (hideDupes) r = r.filter((t) => !isDup(t));
    // Quality gate: a real project earns holders; a thin/scam launch has a handful (KLO646 = 3, GLASSHOUSE
    // = 12). Hide sub-50-holder pools by default — a token pops back in the moment it crosses 50. Core
    // ecosystem assets (USDC, cirBTC) are always exempt. Unknown holder count is treated as below the bar.
    r = r.filter((t) => t.isEcosystem || (t.holders ?? 0) >= MIN_HOLDERS); // always hide sub-50-holder pools
    if (!showInactive) r = r.filter(active); // no real trading in 24h = not on the default board
    // Value a token exposes for the active sort key (null = "no data", always sorts last).
    const val = (t: Token): number | null => (
      sort === 'volume' ? t.volume24h
      : sort === 'change24h' ? t.change24h
      : sort === 'change1h' ? t.change1h
      : sort === 'age' ? t.createdAt
      : (t as any)[sort]) ?? null; // liq | mcap | holders | price
    return [...r].sort((a, b) => {
      if (sort === 'name') { const c = a.name.localeCompare(b.name); return dir === 'asc' ? c : -c; }
      const av = val(a), bv = val(b);
      if (av == null && bv == null) return 0;
      if (av == null) return 1;   // nulls last, regardless of direction
      if (bv == null) return -1;
      return dir === 'desc' ? bv - av : av - bv;
    });
  })();


  const ecoCount = tokens.filter((t) => t.isEcosystem).length;

  // Home DASHBOARD data — one panel, three tabs. Impersonators (non-canonical duplicate tickers) are always
  // dropped so a wash-inflated fake never features. Top Liquidity + Movers also require >=50 holders (a
  // "best of" list shouldn't show thin scams); the New tab keeps every fresh launch (they're small by nature).
  const notDup = (t: Token) => !isDup(t);
  const quality = (t: Token) => notDup(t) && (t.isEcosystem || (t.holders ?? 0) >= MIN_HOLDERS) && active(t);
  const launchpadCount = tokens.filter((t) => t.launchpad && quality(t)).length;
  const launchpadLegend = (() => {
    const n = new Map<string, number>();
    for (const t of tokens) if (t.launchpad && quality(t)) n.set(t.launchpad, (n.get(t.launchpad) ?? 0) + 1);
    return [...n.entries()].sort((a, b) => b[1] - a[1]).map(([label, c]) => ({ label, desc: `${LP_DESC[label] || `Minted by the ${label} contract on Arc.`} ${c} active.` }));
  })(); // eslint-disable-line // actively traded launchpad tokens, not every junk launch
  // Swap token picker: the SAME filter as the board — one real token per ticker, no fakes/flagged rows (09-26: the picker
  // listed three "ARGUS", a fake DIVIDEND…). Pinned/core first, then actively traded by volume, then the rest by liquidity.
  // Any other token is still one paste of its address away.
  const swapTokens = (() => tokens.filter((t) => !isDup(t) && (t.isEcosystem || (t.holders ?? 0) >= MIN_HOLDERS)).sort((a, b) => {
    const rank = (t: Token) => (t.isEcosystem || PINNED.has(t.address.toLowerCase()) ? 2 : active(t) ? 1 : 0);
    return rank(b) - rank(a) || (b.volume24h ?? 0) - (a.volume24h ?? 0) || (b.liq ?? 0) - (a.liq ?? 0);
  }))(); // eslint-disable-line
  const trending = (() => [...tokens].filter((t) => t.liq != null && quality(t)).sort(byLiq).slice(0, 8))(); // eslint-disable-line
  const launches = (() => [...tokens].filter((t) => t.launchpad && t.createdAt != null && notDup(t) && active(t)) // a launch nobody trades is spam
    .sort((a, b) => (b.createdAt ?? 0) - (a.createdAt ?? 0)).slice(0, 8))(); // eslint-disable-line
  const movers = (() => [...tokens].filter((t) => t.change24h != null && t.liq != null && quality(t))
    .sort((a, b) => (b.change24h ?? 0) - (a.change24h ?? 0)).slice(0, 8))(); // eslint-disable-line
  const dashStats = (() => ({
    count: tokens.filter((t) => quality(t)).length, // real, actively traded tokens — not every junk pool ever created
    // One token per ticker: copycats of a real coin (a fake "ARGUS" claimed $2.99M, 09-24) are not market volume.
    // Only tokens that pass the screener's own quality bar (not a dup/fake, 50+ holders or a core asset) — 4-holder bot
    // tokens washing $700K/day each had pushed the total to $27M (09-25).
    vol24: tokens.filter((t) => quality(t)).reduce((s, t) => s + (t.volume24h ?? 0), 0),
    newToday: tokens.filter((t) => t.createdAt != null && Date.now() - t.createdAt < 86400000 && notDup(t) && active(t)).length,
    tracked: tokens.length, // every token the on-chain indexer reads (junk included) — what we TRACK
    // DEX liquidity on Arc: every real token's pools summed (no fakes/dups/flagged rows, 50+ holders or core; the hard
    // rules already capped every row) — active and quiet tokens alike.
    tvl: tokens.filter((t) => notDup(t) && (t.isEcosystem || (t.holders ?? 0) >= MIN_HOLDERS)).reduce((s, t) => s + (t.liq ?? 0), 0),
  }))(); // eslint-disable-line
  const heroMatches = (() => {
    const s = heroQ.trim().toLowerCase(); if (s.length < 1) return [] as Token[];
    if (s.startsWith('0x')) return tokens.filter((t) => t.address.toLowerCase().startsWith(s)).slice(0, 7);
    return tokens
      .filter((t) => !((tickerCount.get((t.symbol || '').toUpperCase()) ?? 0) > 1 && !canonical.has(t.address.toLowerCase())))
      .map((t) => { const sym = (t.symbol || '').toLowerCase(), nm = (t.name || '').toLowerCase();
        const rank = sym === s ? 0 : sym.startsWith(s) ? 1 : nm.startsWith(s) ? 2 : (sym.includes(s) || nm.includes(s)) ? 3 : -1; return { t, rank }; })
      .filter((x) => x.rank >= 0)
      .sort((a, b) => a.rank - b.rank || (b.t.liq ?? 0) - (a.t.liq ?? 0))
      .slice(0, 7).map((x) => x.t);
  })();
  return { rows, dupCount, ecoCount, launchpadCount, launchpadLegend, swapTokens, trending, launches, movers, dashStats, heroMatches };
}
